export const styles = {
  root: { minHeight: "100vh", background: "#000", color: "#c8c8c8", fontFamily: "'Courier New', 'Lucida Console', monospace", position: "relative", overflow: "hidden" },
  scanlines: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(0,0,0,0.15) 2px, rgba(0,0,0,0.15) 4px)", pointerEvents: "none", zIndex: 999 },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 24px", borderBottom: "1px solid #1a1a1a", background: "#000", flexWrap: "wrap", gap: 12 },
  headerLeft: { display: "flex", alignItems: "center", gap: 14 },
  logo: { fontSize: 32, color: "#00ff91", lineHeight: 1 },
  logoText: { fontSize: 15, fontWeight: "bold", letterSpacing: 4, color: "#00ff91" },
  logoSub: { fontSize: 9, color: "#333", letterSpacing: 3, marginTop: 2 },
  timerBox: { display: "flex", alignItems: "center", gap: 10, background: "#0a0a0a", border: "1px solid #1e1e1e", borderRadius: 4, padding: "8px 16px", flexWrap: "wrap" },
  timerLabel: { fontSize: 9, color: "#333", letterSpacing: 3 },
  timerDisplay: { fontSize: 20, fontWeight: "bold", color: "#00ff91", letterSpacing: 3, fontVariantNumeric: "tabular-nums" },
  timerBtns: { display: "flex", gap: 6 },
  timerBtn: { fontSize: 9, padding: "4px 10px", border: "1px solid", borderRadius: 2, cursor: "pointer", letterSpacing: 1, fontFamily: "inherit" },
  tabNav: { display: "flex", gap: 0, borderBottom: "1px solid #111", background: "#000" },
  tab: { flex: 1, padding: "12px 0", background: "transparent", border: "none", borderBottom: "2px solid transparent", color: "#444", fontSize: 10, letterSpacing: 3, cursor: "pointer", fontFamily: "inherit", transition: "all 0.15s" },
  tabActive: { color: "#00ff91", borderBottom: "2px solid #00ff91", background: "#001a0e" },
  main: { maxWidth: 860, margin: "0 auto", padding: 24 },
  panel: { display: "flex", flexDirection: "column", gap: 16 },
  sectionTitle: { fontSize: 9, letterSpacing: 4, color: "#333", marginBottom: 4 },
  offlineBadge: { background: "#001a0e", border: "1px solid #00ff9133", borderRadius: 2, padding: "10px 14px", fontSize: 10, color: "#00ff91", letterSpacing: 1, lineHeight: 1.6 },
  textarea: { width: "100%", boxSizing: "border-box", background: "#080808", border: "1px solid #1e1e1e", color: "#b0b0b0", fontFamily: "inherit", fontSize: 12, padding: 16, resize: "vertical", outline: "none", borderRadius: 2, lineHeight: 1.6 },
  foundTechs: { display: "flex", flexWrap: "wrap", gap: 6, alignItems: "center" },
  techPill: { padding: "3px 8px", background: "#001a0e", border: "1px solid #00ff9133", color: "#00ff91", fontSize: 9, letterSpacing: 2, borderRadius: 2 },
  primaryBtn: { padding: "12px 24px", background: "#001a0e", border: "1px solid #00ff91", color: "#00ff91", fontSize: 10, letterSpacing: 3, cursor: "pointer", fontFamily: "inherit", borderRadius: 2, transition: "all 0.15s" },
  ghostBtn: { padding: "12px 24px", background: "#ffffff08", border: "1px solid #333", color: "#aaa", fontSize: 10, letterSpacing: 3, cursor: "pointer", fontFamily: "inherit", borderRadius: 2 },
  divider: { display: "flex", alignItems: "center", gap: 12 },
  dividerLine: { flex: 1, height: 1, background: "#111" },
  dividerText: { fontSize: 9, letterSpacing: 3, color: "#222", whiteSpace: "nowrap" },
  urlRow: { display: "flex", gap: 8 },
  urlInput: { flex: 1, background: "#080808", border: "1px solid #1e1e1e", color: "#b0b0b0", fontFamily: "inherit", fontSize: 12, padding: "10px 14px", outline: "none", borderRadius: 2 },
  scrapeBtn: { padding: "10px 20px", background: "#0a0a0a", border: "1px solid #333", color: "#888", fontSize: 10, letterSpacing: 2, cursor: "pointer", fontFamily: "inherit", borderRadius: 2 },
  freeApis: { background: "#050505", border: "1px solid #111", borderRadius: 2, padding: 16, display: "flex", flexDirection: "column", gap: 8 },
  apiRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "6px 0", borderBottom: "1px solid #0e0e0e" },
  apiName: { fontSize: 11, color: "#00ff91" },
  apiNote: { fontSize: 10, color: "#444" },
  error: { background: "#1a0000", border: "1px solid #ff2d2d", color: "#ff2d2d", padding: 12, fontSize: 11, borderRadius: 2 },
  browseHeader: { display: "flex", flexDirection: "column", gap: 8 },
  filterRow: { display: "flex", flexWrap: "wrap", gap: 6 },
  filterChip: { padding: "4px 10px", background: "#0a0a0a", border: "1px solid #222", color: "#444", fontSize: 9, letterSpacing: 2, cursor: "pointer", fontFamily: "inherit", borderRadius: 2 },
  filterChipActive: { background: "#001a0e", borderColor: "#00ff91", color: "#00ff91" },
  dbList: { display: "flex", flexDirection: "column", gap: 4, maxHeight: "60vh", overflowY: "auto" },
  dbRow: { display: "flex", alignItems: "flex-start", gap: 12, padding: "10px 12px", background: "#060606", border: "1px solid #111", borderRadius: 2 },
  dbRowLeft: { display: "flex", flexDirection: "column", gap: 4, minWidth: 80 },
  dbIndex: { fontSize: 9, color: "#222" },
  dbTech: { fontSize: 9, color: "#00ff91", letterSpacing: 2 },
  dbQuestion: { fontSize: 12, color: "#888", lineHeight: 1.5 },
  cardWrapper: { display: "flex", flexDirection: "column", alignItems: "center", gap: 20 },
  cardMeta: { width: "100%", maxWidth: 640, display: "flex", justifyContent: "space-between", alignItems: "center" },
  cardTech: { fontSize: 9, letterSpacing: 4, color: "#00ff91" },
  cardCount: { fontSize: 9, letterSpacing: 2, color: "#333" },
  cardScene: { width: "100%", maxWidth: 640, height: 340, perspective: "1000px", cursor: "pointer" },
  cardInner: { width: "100%", height: "100%", position: "relative", transformStyle: "preserve-3d", transition: "transform 0.55s cubic-bezier(0.4, 0, 0.2, 1)" },
  cardFront: { position: "absolute", inset: 0, background: "#060606", border: "1px solid #1e1e1e", borderRadius: 4, padding: 32, display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", backfaceVisibility: "hidden" },
  cardBack: { position: "absolute", inset: 0, background: "#001a0e", border: "1px solid #00ff9133", borderRadius: 4, padding: 32, display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", backfaceVisibility: "hidden", transform: "rotateY(180deg)" },
  cardCorner: { position: "absolute", top: 16, left: 20, fontSize: 11, letterSpacing: 3, color: "#333" },
  cardQuestion: { fontSize: 16, color: "#e0e0e0", textAlign: "center", lineHeight: 1.6, margin: 0 },
  cardAnswer: { fontSize: 13, color: "#b0e0c8", textAlign: "center", lineHeight: 1.7, margin: 0 },
  flipHint: { position: "absolute", bottom: 16, right: 20, fontSize: 9, color: "#222", letterSpacing: 2 },
  cardNav: { display: "flex", gap: 16, width: "100%", maxWidth: 640 },
  navBtn: { flex: 1, padding: "12px 0", background: "#080808", border: "1px solid #1e1e1e", color: "#555", fontSize: 10, letterSpacing: 3, cursor: "pointer", fontFamily: "inherit", borderRadius: 2 },
  navBtnNext: { borderColor: "#00ff9133", color: "#00ff91" },
  emptyState: { display: "flex", flexDirection: "column", alignItems: "center", gap: 16, padding: "60px 0" },
  emptyIcon: { fontSize: 48, color: "#1a1a1a" },
  emptyText: { fontSize: 14, color: "#444", letterSpacing: 2 },
  emptySub: { fontSize: 11, color: "#2a2a2a", textAlign: "center" },
  emptyActions: { display: "flex", gap: 12, flexWrap: "wrap", justifyContent: "center" },
};
